# Generated by Django 5.1.7 on 2025-03-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
