# Generated by Django 5.1.7 on 2025-03-12 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carType',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_owner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='company',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('owner_contact', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('owner_adress', models.TextField()),
                ('car_model', models.CharField(max_length=60)),
                ('car_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Car number must be in the format 'MH12AB1234'.", regex='^[A-Z]{2}\\d{2}[A-Z]{2}\\d{4}$')])),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('carType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cartype')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
        migrations.AddField(
            model_name='carreport',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
    ]
