# Generated by Django 5.1.7 on 2025-03-29 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbook',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
        migrations.AlterField(
            model_name='carbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
