# Generated by Django 5.1.7 on 2025-03-12 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_car_cartype_remove_car_car_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='carType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cartype'),
        ),
        migrations.AlterField(
            model_name='carbook',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
        migrations.AlterField(
            model_name='carbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
