# Generated by Django 5.1.7 on 2025-03-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agent_cartype_alter_carbook_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='carType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cartype'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='car_image',
            field=models.ImageField(default=1, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='car',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
        migrations.AlterField(
            model_name='carbook',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
        migrations.AlterField(
            model_name='carbook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
        migrations.AlterField(
            model_name='carreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
