# Generated by Django 5.1.7 on 2025-03-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_agent_cartype_alter_agent_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbook',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.agent'),
        ),
    ]
